/**
 * Local image check for the member directory and the events calendar.
 *
 *   npm run images          (also runs automatically via `prebuild` and `predev`)
 *
 * src/data/members.ts and src/data/events.ts reference their images as
 * site-absolute paths into public/. This script walks every one of those
 * paths and:
 *
 *   - measures each file that exists and records it in
 *     src/data/local-images.json, which is what the site reads. An image the
 *     manifest does not list renders the branded placeholder instead of a
 *     broken <img>, so a file that has not been dropped in yet never breaks a
 *     page.
 *   - prints every referenced file that is missing, and every file whose
 *     contents do not match its extension (a PNG saved as .jpg).
 *
 * It never fails the build: a missing image is content still to come, not an
 * error.
 *
 * Why a manifest rather than checking the disk at render time: pages are
 * regenerated by ISR on Vercel, where public/ is served from the CDN and is not
 * guaranteed to exist on the function's filesystem. The manifest is bundled
 * with the code, so it answers the same way at build time and at revalidation.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { members } from '../src/data/members';
import { events, eventSeries } from '../src/data/events';
import { measure, sniff } from './image-header';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST_PATH = path.join(ROOT, 'src', 'data', 'local-images.json');

interface Ref {
  src: string;
  owner: string;
  kind: string;
}

function collect(): Ref[] {
  const refs: Ref[] = [];
  for (const m of members) {
    const person = [m.firstName, m.lastName].filter(Boolean).join(' ');
    if (m.logo) refs.push({ src: m.logo, owner: m.business, kind: 'logo' });
    if (m.photo) refs.push({ src: m.photo, owner: person || m.business, kind: 'headshot' });
  }
  for (const e of events) {
    if (e.img) refs.push({ src: e.img, owner: e.title, kind: 'event image' });
    for (const g of e.gallery ?? []) refs.push({ src: g, owner: e.title, kind: 'event gallery' });
  }
  for (const s of eventSeries) {
    if (s.logo) refs.push({ src: s.logo, owner: s.name, kind: 'series logo' });
  }
  return refs;
}

async function main() {
  const refs = collect();
  const manifest: Record<string, { width: number; height: number }> = {};
  const missing: Ref[] = [];
  const problems: string[] = [];

  for (const src of [...new Set(refs.map((r) => r.src))].sort()) {
    const users = refs.filter((r) => r.src === src);

    if (!src.startsWith('/') || src.startsWith('//')) {
      problems.push(`${src} — must be a local path starting with "/" (used by ${users[0].owner})`);
      continue;
    }

    const file = path.join(ROOT, 'public', ...src.split('/'));
    if (!existsSync(file)) {
      missing.push(...users);
      continue;
    }

    const buf = await readFile(file);
    const actual = sniff(buf);
    const dims = actual ? measure(buf, actual) : null;
    if (!actual || !dims) {
      problems.push(`${src} — not a readable jpg/png/webp; it will show the placeholder`);
      continue;
    }

    const declared = path.extname(src).slice(1).toLowerCase().replace('jpeg', 'jpg');
    if (declared !== actual) {
      problems.push(`${src} — file is really a ${actual.toUpperCase()}; rename it or convert it`);
    }

    manifest[src] = { width: dims.width, height: dims.height };
  }

  const next = `${JSON.stringify(manifest, null, 2)}\n`;
  const prev = existsSync(MANIFEST_PATH) ? await readFile(MANIFEST_PATH, 'utf8') : '';
  if (next !== prev) await writeFile(MANIFEST_PATH, next);

  const found = Object.keys(manifest).length;
  const total = new Set(refs.map((r) => r.src)).size;
  console.log(`[images] ${found} of ${total} referenced images present`);

  if (missing.length) {
    console.log(`[images] missing (${missing.length}):`);
    for (const r of missing) console.log(`  ${r.src}  —  ${r.owner} (${r.kind})`);
  }
  if (problems.length) {
    console.log(`[images] problems (${problems.length}):`);
    for (const p of problems) console.log(`  ${p}`);
  }
}

main().catch((err) => {
  // Never fail the build over images; the site falls back to placeholders.
  console.error('[images] check failed, continuing:', err);
});
